app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/admin/tasks');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin/tasks', 'as' => 'admin.tasks.'], function () {
    // Tasks
    Route::get('/', 'TaskController@index')->name('index');
    Route::get('getTasks/{status}', 'TaskController@index')->name('index');
    Route::post('init', 'TaskController@init')->name('init');
    Route::get('{id}/edit', 'TaskController@edit')->name('edit');
    Route::delete('{id}/delete', 'TaskController@delete')->name('delete');
    Route::get('create', 'TaskController@create')->name('create');
    Route::post('store', 'TaskController@store')->name('store');
    Route::patch('{id}/update', 'TaskController@update')->name('update');
    Route::get('{id}/details', 'TaskController@details')->name('details');
    // Logs
    Route::get('{id}/logs', 'TaskController@logs')->name('logs');
    Route::post('addLog', 'TaskController@addLog')->name('add_log');
    Route::delete('{id}/delete_log', 'TaskController@deleteLog')->name('delete_log');
    Route::post('{id}/{status}/updateStatus', 'TaskController@updateStatus')->name('update_status');
    Route::post('{id}/{status}/{comment}/updateApprovalStatus', 'TaskController@updateApprovalStatus')->name('update_approval_status');
    Route::post('updateTaskStatus', 'TaskController@updateTaskStatus')->name('update_task_status');
    Route::post('/checkDay', 'TaskController@checkDay')->name('check_day');
    // Calendar
    Route::get('{user_id}/calendar', 'TaskController@calendar')->name('calendar');
    
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin/users', 'as' => 'admin.users.'], function () {
    Route::get('/{status}', 'UserController@index')->name('index');

    Route::post('init', 'UserController@init')->name('init');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
    Route::post('{id}/recommission', 'UserController@recommission')->name('recommission');
    Route::get('create', 'UserController@create')->name('create');
    Route::delete('delete_multiple', 'UserController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'UserController@store')->name('store');
    Route::patch('{id}/update', 'UserController@update')->name('update');
});



Route::auth();

Route::get('/home', 'HomeController@index');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;
use Hash;

class UserController extends Controller
{
    public function index($status){
    	$users = User::where('user_type','User')->where('decommissioned',$status)->get();
        $data = [];
        $data['partialView'] = 'users.list';
        $data['status'] = $status;
        $data['users'] = $users;
    	return view('users.index',$data);
    }

    public function init(){
    	
    	return response()->json([
                    'url' => route('admin.users.edit', ['id' => 0])
        ]);
    }
    
    

    
    public function edit($id)
    {
        $user = User::find($id);
        $data = [];
        $data['partialView'] = 'users.form';
        $data['user'] = $user;
        

        return view('tasks.index',$data);

    }


    public function store(Request $request)
    {
        $data = $request->input();
        $user = User::find($data['id']);
        if(!$user){
        	$user = new User();
        }
        $user->name = $data['name'];
        $user->email = $data['email'];
        $user->password = Hash::make($data['password']);
        $user->user_type = 'User';
        $user->save();
    }

    public function delete($id){
        $user = User::find($id);
        $user->decommissioned = 1;
        $user->save();
        return 'Success';
    }

    public function recommission($id){
        $user = User::find($id);
        $user->decommissioned = 0;
        $user->save();
        return 'Success';    
    }
}

resources/views/users/form.blade.php
<form class="ajax_form" method="post" action="/admin/users/store">
{{ csrf_field() }}
  <input type="hidden" name="id" id="id" value="<?php if(isset($user)){?>{{$user->id}}<?php ;}?>" />
<div  id="main-form" novalidate  class="form-horizontal form"> 
    <div class="global-errors alert alert-danger hidden"></div>
            <div class="form-body">
<div class="mt-element-ribbon bg-grey-steel">
                    <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                        <div class="ribbon-sub ribbon-clip"></div> User Details </div>
                    <div class="ribbon-content">
                        
                        <div class="form-group">
                            <label>Name</label>
                            <input name="name" class="form-control" value="<?php if(isset($user)){?>{{$user->name}}<?php ;}?>">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input name="email" class="form-control" value="<?php if(isset($user)){?>{{$user->email}}<?php ;}?>">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control" >
                        </div>
                        <input type="submit" name="button" id="button" value="Submit" />
                        
                        
                    </div>
              </div>
    </div>
                </div>

</form>

resources/views/users/index.blade.php
<?php
$i = 'users';
$j = $status;
?>
@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/dragula/dragula.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.css')}}"/>
@endSection

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jsvalidation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/dragula/dragula.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.js')}}"></script>
@endSection

@section('page_js')
<script type="text/javascript" src="{{asset('assets/scripts.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/users.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
Users
@stop

@section('page_title')
Users
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/users/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Users
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <button class="btn green" id="add_new_course" data-action="{{route('admin.users.init')}}">
                            Add New <i class="fa fa-plus"></i>
                        </button>                        
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">
            <thead>
                <tr class="tr-head">
                    <th valign="middle">
                        Name
                    </th>
                    <th valign="middle">
                        Email
                    </th>
                    <th valign="middle">
                        Created at
                    </th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                <tr class="odd gradeX" id="data-row-{{$user->id}}">
                    <td valign="middle">
                        {{$user->name}}
                    </td>
                    <td valign="middle">{{$user->email}}
                        
                    </td>
                    <td valign="middle">
                        {{$user->created_at}}
                    </td>
                    <td valign="middle">
                        <a href="{{route('admin.users.edit',['id'=>$user->id])}}" class="btn green pjax-link" ><i class="fa fa-edit"></i> Edit</a> 
                        @if($user->decommissioned ==0)<a href="{{route('admin.users.delete',['id'=>$user->id])}}" class="btn red remove-course" ><i class="fa fa-remove"></i> Decommission</a>@endif 
                        @if($user->decommissioned ==1)<a href="{{route('admin.users.recommission',['id'=>$user->id])}}" class="btn grey recommission_user" ><i class="fa fa-play"></i> Recommission</a>@endif 
                        <a href="{{route('admin.tasks.calendar',['user_id'=>$user->id])}}" class="btn blue" target="_blank" ><i class="fa fa-calendar"></i> Calendar</a> 
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>