app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/admin/tasks');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin/tasks', 'as' => 'admin.tasks.'], function () {
    // Tasks
    Route::get('/', 'TaskController@index')->name('index');
    Route::get('getTasks/{status}', 'TaskController@index')->name('index');
    Route::post('init', 'TaskController@init')->name('init');
    Route::get('{id}/edit', 'TaskController@edit')->name('edit');
    Route::delete('{id}/delete', 'TaskController@delete')->name('delete');
    Route::get('create', 'TaskController@create')->name('create');
    Route::post('store', 'TaskController@store')->name('store');
    Route::patch('{id}/update', 'TaskController@update')->name('update');
    Route::get('{id}/details', 'TaskController@details')->name('details');
    // Logs
    Route::get('{id}/logs', 'TaskController@logs')->name('logs');
    Route::post('addLog', 'TaskController@addLog')->name('add_log');
    Route::delete('{id}/delete_log', 'TaskController@deleteLog')->name('delete_log');
    Route::post('{id}/{status}/updateStatus', 'TaskController@updateStatus')->name('update_status');
    Route::post('{id}/{status}/{comment}/updateApprovalStatus', 'TaskController@updateApprovalStatus')->name('update_approval_status');
    Route::post('updateTaskStatus', 'TaskController@updateTaskStatus')->name('update_task_status');
    Route::post('/checkDay', 'TaskController@checkDay')->name('check_day');
    // Calendar
    Route::get('{user_id}/calendar', 'TaskController@calendar')->name('calendar');
    
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin/users', 'as' => 'admin.users.'], function () {
    Route::get('/{status}', 'UserController@index')->name('index');

    Route::post('init', 'UserController@init')->name('init');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
    Route::post('{id}/recommission', 'UserController@recommission')->name('recommission');
    Route::get('create', 'UserController@create')->name('create');
    Route::delete('delete_multiple', 'UserController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'UserController@store')->name('store');
    Route::patch('{id}/update', 'UserController@update')->name('update');
});



Route::auth();

Route::get('/home', 'HomeController@index');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    public function getUser(){
    	return $this->hasOne('App\User','id','user_id');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Task;
use App\task_progress;
use App\User;
use App\Language;
use Auth;
use DB;
use App\Color;
use Mail;

class TaskController extends Controller
{
    protected $logged_user;
    public function __construct(){
        $logged_user  = Auth::user();
        $this->logged_user = $logged_user;
        if($this->logged_user->decommissioned == 1){
            //return redirect('/logout');
            exit();
        }
    }
    public function index($status="All"){

        // if the resource allocator is logged in -> get all tasks
        if($this->logged_user->user_type == "Allocator"){
            $tasks = Task::where('approval_status',$status)->get();
            if($status == "All"){
                return redirect('/admin/tasks/getTasks/Pending');
            }
        }
        // if a normal user is logged in -> get only his tasks
        if($this->logged_user->user_type == "User"){
            if($status == "All"){
                return redirect('/admin/tasks/getTasks/Running');
            }
            if($status == "Running"){
                $status1 = array('Running','Paused');
            }else{
                $status1 = array('Finished');
            }
            $tasks =Task::where('user_id',$this->logged_user->id)->whereIn('status',$status1)->get();
            $updateNotification =Task::where('user_id',$this->logged_user->id)->whereIn('status',$status1)->update(['notification'=>0]);

        }
        $data = [];
        $data['status'] = $status;
        $data['partialView'] = 'tasks.list';
        $data['tasks'] = $tasks;
        $data['user_type'] = $this->logged_user->user_type;
    	return view('tasks.index',$data);
    }

    public function init(){
    	
    	return response()->json([
                    'url' => route('admin.tasks.edit', ['id' => 0])
        ]);
    }
    
    

    
    public function edit($id)
    {
        $task = Task::find($id);
        $data = [];
        $data['partialView'] = 'tasks.form';
        $data['task'] = $task;
        $data['languages'] = Language::orderBy('language')->get();
        return view('tasks.index',$data);

    }

    public function details($id){
        $task = Task::find($id);
        $data = [];
        $data['partialView'] = 'tasks.task_details';
        $data['task'] = $task;
        return view('tasks.logs',$data);
        
    }

    public function store(Request $request)
    {
        $data = $request->input();
        $task_check = Task::find($data['id']);
        if(!$task_check){
            $task = new Task();
            $last_task = Task::where('user_id',$this->logged_user->id)->orderBy('id','desc')->first();
            if(isset($last_task) && $last_task->color_id != 30){
                $new_color_id = $last_task->color_id + 1;    
            }else{
                $new_color_id = 1;
            }
            $task->color_id = $new_color_id;
        }else{
            $task = $task_check;
        }
        // Validate task start time
        $response = $this->validateTask(strtotime($data['start_time']),"0",$this->logged_user->id);
        
        if($response['type'] == "error"){
            return response()->json([
                'data' => $response
            ]);    
        }
        // Set the task attributes
        $task->name = $data['name'];
        $task->user_id = $this->logged_user->id;
        $task->start_time = $data['start_time'];
        $task->last_start_time = $data['start_time'];
        $task->software = $data['software'];
        $task->estimated_time_hours = $data['estimated_time_hours'];
        $task->estimated_time_mins = $data['estimated_time_mins'];
        $task->project_type = $data['project_type'];
        $task->language_source = $data['source'];
        $task->language_target = $data['target'];
        $task->email_subject = $data['email_subject'];
        $task->share_path = $data['share_path'];
        $task->save();

        if(!$task_check){
            $log = new task_progress();
            $log->task_id = $task->id;
            $log->start_time = $data['start_time'];
            $log->user_id = $this->logged_user->id;
            $log->added_by_id = $this->logged_user->id;
            $log->save();
        }
        // Ready the response for the success
        $response = [];
        $response['type'] = 'success';
        $response['msg'] = 'Successfully added';
        $response['task_id'] = $log->task_id;
        return response()->json([
            'data' => $response
        ]);

    }

    public function delete($id){
        $task = Task::find($id)->delete();
        return 'Success';
    }

    public function logs($id)
    {
        $task = Task::find($id);
        $logs = task_progress::where('task_id',$id)->orderBy('start_time','asc')->get();
        $data = [];
        $data['partialView'] = 'tasks.logs_detail';
        $data['task'] = $task;
        $data['logs'] = $logs;
        $data['users'] = User::where('user_type','User')->orderBy('name')->get();

        return view('tasks.logs',$data);

    }

    public function addLog(Request $request){
        $data = $request->input(); 
        $start_time = strtotime($data['start_time']);
        $end_time = strtotime($data['end_time']);
        //Validate the task
        $response = $this->validateTask($start_time,$end_time,$data['user_id']);
        if($response['type'] == "error"){
            return response()->json([
                'data' => $response
            ]);    
        }
        // create log and save it
        $log = new task_progress();
        $log->start_time = $data['start_time'];
        $log->end_time = $data['end_time'];
        $log->task_id = $data['task_id'];
        $log->user_id = $data['user_id'];
        $log->added_by_id = $this->logged_user->id;
        $log->save();

        //Update task total duration
        $log_duration = strtotime($log->end_time) - strtotime($log->start_time);
        $task = Task::find($log->task_id);
        $task->duration = $task->duration + $log_duration;
        $task->save();
       $this->updateStartedOn($task->id);

        // Ready the response for the success
        $response = [];
        $response['type'] = 'success';
        $response['msg'] = 'Successfully added';
        $response['task_id'] = $log->task_id;
        return response()->json([
            'data' => $response
        ]);
    }

    public function validateTask($start_time,$end_time,$user_id){
        $response = [];
        $response['type'] = 'success';
        $response['msg'] = 'Successfully added';
        
        $start_time = date("Y-m-d H:i:s",$start_time);
        if($end_time!= "0"){
            $end_time = date("Y-m-d H:i:s",$end_time);
        }
        // Get logs interfering with start time
        $check_interfere_start = task_progress::where('start_time' ,'<=',$start_time)->where('end_time' ,'>',$start_time)->where('user_id',$user_id)->count();
        
        // Get logs interfering with end time
        $check_interfere_end = task_progress::where('start_time' ,'<',$end_time)->where('end_time' ,'>=',$end_time)->where('user_id',$user_id)->count();
        // if the insertion is from adding new task pass this check
        if($end_time == "0"){
            $check_interfere_end = 0;    
        }

        //Check if start time greater than end time
        if($start_time>=$end_time && $end_time != "0"){
            
            $response['type'] = 'error';
            $response['msg'] = 'Start time is bigger than end time';
            
           
             
        }

        //Check if the interfering tasks exist
        if($check_interfere_start > 0 || $check_interfere_end > 0){
            
            $response['type'] = 'error';
            $response['msg'] = 'The interval inserted is interfering with an old log';
            
            
             
        }
        return $response;


    }
    public function deleteLog($id){
        $log = task_progress::find($id);
        if($log->end_time){
            $log_duration = strtotime($log->end_time) - strtotime($log->start_time);
            $task = Task::find($log->task_id);
            $task->duration = $task->duration - $log_duration;
            
        }
        $remaining_logs = task_progress::where('task_id',$log->task_id)->count();
        if($remaining_logs>=2){
            $task->save();
            $log->delete();
           $this->updateStartedOn($task->id);
        }else{
            abort(404);
        }
        return 'Success';
    }

    public function updateStatus($id,$status){
        $task = Task::find($id);
        $task->status = $status;
        if($status == "Finished"){
            $task->approval_status = "Pending";
        }else{
            $task->approval_status = "None"; 
        }
        $task->save();
    }
    public function updateApprovalStatus($id,$status,$comment){
        $task = Task::find($id);
        $user = User::find($task->user_id);
        $task->approval_status = $status;
        $task->comment = $comment;
        if($task->approval_status != "Pending"){
            $task->notification = 1;
            Mail::send('emails.approval', ['user' => $user,'task' => $task  ], function ($m) use ($user,$task) {
                $m->from('workflow@arabiclocalizer.info', 'DTP Factory');

                $m->to('mtarek@arabiclocalizer.com', 'Resource Allocator')->subject($task->name.' Approved');
                
            });
        }
        $task->save();
        $remaining_pending = Task::where('approval_status','Pending')->count();
        return $remaining_pending;
    }
    public function updateTaskStatus(Request $Request){
        $data = $Request->input();
        $response = [];
        $response['update_running'] = 0;
        $task = Task::find($data['task_id']);
        $user = User::find($task->user_id);

resources/views/tasks/detail.blade.php
<?php
$i = 'tasks';
$j = 'tasks';
?>
@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/dragula/dragula.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.css')}}"/>
<style>
.page-header,.page-footer,.page-title{
	display:none !important;
}
.row{
	padding-left:0 !important;
	padding-right:0 !important;
	margin-left:0 !important;
	margin-right:0 !important;
}
.bootstrap-switch{
	float:right;
}
.col-sm-6{
	margin:0 !important;
	padding:0 !important;
}
th,td{
	padding:10px !important;
}
</style>
@endSection

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jsvalidation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/dragula/dragula.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.js')}}"></script>
@endSection

@section('page_js')
<script type="text/javascript" src="{{asset('assets/scripts.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/logs.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
{{$task->name}}
@stop

@section('page_title')
{{$task->name}}
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/tasks/details.blade.php
<div class="row">
<div class="col-sm-6">
<h3 style="text-align:left; margin-top:0;">{{$task->name}} Logs</h3>
</div>
<div class="col-sm-6 hide">
<input name="task-status" @if($task->status == "Finished") disabled checked @endif type="checkbox"  class="make-switch pull-right" data-on-color="success" data-off-color="info" data-on-text="Finished" data-off-text="Running">
</div>
</div>
<table class="table table-striped table-bordered table-hover table-dt"  >
                <thead>
                    <tr class="tr-head">
                        <th valign="middle">
                            Start time
                        </th>
                        <th valign="middle">
                            End time
                        </th>
                        <th valign="middle">User</th>
                        <th valign="middle">By</th>
                        <th valign="middle">
                            Created at
                        </th>
                        <th valign="middle">
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($logs as $log)
                    <tr class="odd gradeX" id="data-row-{{$log->id}}">
                        <td valign="middle">
                            {{ Carbon\Carbon::parse($log->start_time)->format('D d, M Y H:i a') }}
                        </td>
                        <td valign="middle">
                        @if($log->end_time){{ Carbon\Carbon::parse($log->end_time)->format('D d, M Y H:i a') }}@endif
                        @if(!$log->end_time) Null @endif    
                        </td>
                        <td valign="middle">{{$log->getUser->name}}</td>
                        <td valign="middle">{{$log->getAddedBy->name}}</td>
                        <td valign="middle">
                            
                            {{ Carbon\Carbon::parse($log->created_at)->format('D d, M Y H:i a') }}
                        </td>
                        <td valign="middle">
                        @if(($task->status != "Finished" && $log->added_by_id == Auth::user()->id) || Auth::user()->user_type == "Allocator")
                            <a href="{{route('admin.tasks.delete_log',['id'=>$log->id])}}" class="btn red remove-course" ><i class="fa fa-remove"></i></a> 
                        @endif    
                        </td>
                    </tr>
                    @endforeach
                    
                </tbody>
            </table>
            @if(Auth::user()->user_type == "Allocator")
<form class="ajax_form" method="post" action="/admin/tasks/addLog">
        <div class="row">
            <div class="col-sm-5">
                <div class="input-group">
                    <span class="input-group-btn">
                         <button class="btn blue" type="button"><i class="fa fa-clock-o"></i> Start Time</button>
                    </span>
                  <input class="form-control timepicker" type="text" name="start_time"> </div>
                <!-- /input-group -->
            </div>
            <div class="col-sm-2">
            <button type="submit" class="btn blue center-block" >Add log</button>
            </div>
          <!-- /.col-md-6 -->
            <div class="col-sm-5">
                <div class="input-group">
                  <input class="form-control timepicker" type="text" name="end_time">
                    <span class="input-group-btn">
                         <button class="btn red" type="button">End Time <i class="fa fa-clock-o"></i></button>
                    </span>
                </div>
                <!-- /input-group -->
            </div>
            <!-- /.col-md-6 -->
        </div>
        
  
        <input type="hidden" name="task_id" id="task_id" value="{{$task->id}}" />
        <input type="hidden" name="user_id" id="user_id" value="{{$task->getUser->id}}"/>
        
        </form>
        @endif

resources/views/tasks/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Tasks
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
    @if(Auth::user()->user_type == "User")
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <button class="btn green" id="add_new_course" data-action="{{route('admin.tasks.init')}}">
                            Add New <i class="fa fa-plus"></i>
                        </button>                        
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
    @endif
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">
            <thead>
                <tr class="tr-head">
                    <th valign="middle">
                        Title
                    </th>
                    <th valign="middle">
                        User
                    </th>
                    <th valign="middle">Email Subject</th>
                    <th valign="middle">Total Duration</th>
                    <th valign="middle">Status</th>
                   @if(Auth::user()->user_type == "Allocator") <th valign="middle">Approval Status</th>@endif
                   @if(Auth::user()->user_type == "User")<th valign="middle">Approval Status</th>@endif
                    <th valign="middle">
                        Started on
                    </th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($tasks as $task)
                <tr class="odd gradeX <?php if($task->notification == 1 && Auth::user()->user_type == "User"){?>success<?php ;}?>" id="data-row-{{$task->id}}">
                    <td valign="middle">
                        <a href="/admin/tasks/{{$task->id}}/details" class="popup">{{$task->name}}</a>
                    </td>
                    <td valign="middle"><?php if(isset($task->getUser->name)){?>{{$task->getUser->name}}<?php ;}?>
                        
                    </td>
                    <td valign="middle">{{$task->email_subject}}</td>
                    <td valign="middle"><?php
					$hours = floor($task->duration/(60*60));
					$mins = floor((($task->duration - ($hours*60*60) )/60));
					echo $hours.":".$mins;
					 ?></td>
                    <td valign="middle">
                    @if(Auth::user()->user_type == "User")
                    @if($task->status != 'Finished')
                    <div class="buttons">
                    <button class="btn blue running_status show_form" data-status="{{$task->status}}" @if($task->status=="Paused")data-type="resume"@endif @if($task->status=="Running")data-type="pause"@endif>
                        @if($task->status=="Paused")<i class="fa fa-pause" aria-hidden="true"></i> @endif
                        @if($task->status=="Running")<i class="fa fa-play" aria-hidden="true"></i> @endif
                        {{$task->status}}
                    </button>
                    @if($task->status=="Running")<button class="btn red show_form" data-type="end"><i class="fa fa-stop" aria-hidden="true"></i> End</button>@endif
                    </div>
                    <div class="timepickerDiv"  style="display:none;">
                    <form class="ajax_form1" action="/admin/tasks/updateTaskStatus"  method="post">
                    <input placeholder="Insert time" type="text" class="form-control timepicker pull-left" name="time" style="width:150px;"  />
                    <input type="hidden" name="task_id" value="{{$task->id}}" />
                    <input type="hidden" name="status" value="{{$task->status}}" />
                    <input type="hidden" name="log_type" value="" class="log_type" />
                    <input type="hidden" name="day" value="<?php echo date("d",strtotime($task->last_start_time));?>"  />
                    
                    <button class="btn blue pull-left submit_log" type="submit"><i class="fa fa-thumbs-up" aria-hidden="true"></i></button>
					<a href="#" class="btn red cancel_update pull-left" ><i class="fa fa-remove"></i> </a>
                    
                    </form>
                    </div>
 					@endif
                    @if($task->status == 'Finished')
                    Finished
                    
                    @endif
                    
                    @endif
                    @if(Auth::user()->user_type == "Allocator")
                    	{{$task->status}}
                    @endif
                    </td>
                   @if(Auth::user()->user_type == "Allocator") <td align="center" valign="middle">@if($task->approval_status == "None"){{$task->approval_status}}@endif 
                   @if($task->approval_status != "None")
                   <select name="task-status" data-task_id="{{$task->id}}" class="approval_select">
                   	<option disabled="disabled" value="Pending" <?php if($task->approval_status == "Pending"){?> selected="selected" <?php ;}?>>Pending</option>
                   	
                   	<option value="Rejected" <?php if($task->approval_status == "Rejected"){?> selected="selected" <?php ;}?>>Approved</option>
                   </select>
                   @endif
                   @if($task->comment!="Ok" && $task->approval_status == "Rejected") <a href="#" class="popovers red" data-container="body" data-trigger="hover" data-placement="top" data-content="{{$task->comment}}" data-original-title="Comment">Comment</a> @endif
                   
                   </td>@endif
                   @if(Auth::user()->user_type == "User")<td align="center" valign="middle">
                   @if($task->approval_status!="Rejected")
                   {{$task->approval_status}} 
                   @endif
                   @if($task->comment!="Ok" && $task->approval_status == "Rejected") <a href="#" class="popovers red" data-container="body" data-trigger="hover" data-placement="top" data-content="{{$task->comment}}" data-original-title="Comment">Approved with a comment</a> @endif</td>@endif
                    <td valign="middle">
                        {{ Carbon\Carbon::parse($task->start_time)->format('D d, M Y H:i') }}
                        
                    </td>
                    <td valign="middle">
                    	@if($task->status != "Finished" || Auth::user()->user_type == "Allocator")
                        <a href="{{route('admin.tasks.edit',['id'=>$task->id])}}" class="btn green pjax-link" ><i class="fa fa-edit"></i> Edit</a> 
                        @endif
                    	@if(Auth::user()->user_type == "Allocator")
                        <a href="{{route('admin.tasks.delete',['id'=>$task->id])}}" class="btn red remove-course" ><i class="fa fa-remove"></i> Delete</a> 
                        @endif
                        @if($task->status != "Finished" || Auth::user()->user_type == "Allocator")
                        <a href="{{route('admin.tasks.logs',['id'=>$task->id])}}" class="btn blue popup" ><i class="fa fa-clock-o"></i> logs</a>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/tasks/logs_detail.blade.php
<div class="row">
<div class="col-sm-6">
<h3 style="text-align:left; margin-top:0;">{{$task->name}} Logs</h3>
</div>
<div class="col-sm-6 hide">
<input name="task-status" @if($task->status == "Finished") disabled checked @endif type="checkbox"  class="make-switch pull-right" data-on-color="success" data-off-color="info" data-on-text="Finished" data-off-text="Running">
</div>
</div>
<table class="table table-striped table-bordered table-hover table-dt"  >
                <thead>
                    <tr class="tr-head">
                        <th valign="middle">
                            Start time
                        </th>
                        <th valign="middle">
                            End time
                        </th>
                        <th valign="middle">User</th>
                        <th valign="middle">By</th>
                        <th valign="middle">
                            Created at
                        </th>
                        <th valign="middle">
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($logs as $log)
                    <tr class="odd gradeX" id="data-row-{{$log->id}}">
                        <td valign="middle">
                            {{ Carbon\Carbon::parse($log->start_time)->format('D d, M Y H:i a') }}
                        </td>
                        <td valign="middle">
                        @if($log->end_time){{ Carbon\Carbon::parse($log->end_time)->format('D d, M Y H:i a') }}@endif
                        @if(!$log->end_time) Null @endif    
                        </td>
                        <td valign="middle">{{$log->getUser->name}}</td>
                        <td valign="middle">{{$log->getAddedBy->name}}</td>
                        <td valign="middle">
                            
                            {{ Carbon\Carbon::parse($log->created_at)->format('D d, M Y H:i a') }}
                        </td>
                        <td valign="middle">
                        @if(($task->status != "Finished" && $log->added_by_id == Auth::user()->id && $log->end_time) || Auth::user()->user_type == "Allocator")
                            <a href="{{route('admin.tasks.delete_log',['id'=>$log->id])}}" class="btn red remove-course" ><i class="fa fa-remove"></i></a> 
                        @endif    
                        </td>
                    </tr>
                    @endforeach
                    
                </tbody>
            </table>
            @if(Auth::user()->user_type == "Allocator")
<form class="ajax_form" method="post" action="/admin/tasks/addLog">
        <div class="row">
            <div class="col-sm-5">
                <div class="input-group">
                    <span class="input-group-btn">
                         <button class="btn blue" type="button"><i class="fa fa-clock-o"></i> Start Time</button>
                    </span>
                  <input class="form-control timepicker" type="text" name="start_time"> </div>
                <!-- /input-group -->
            </div>
            <div class="col-sm-2">
            <button type="submit" class="btn blue center-block" >Add log</button>
            </div>
          <!-- /.col-md-6 -->
            <div class="col-sm-5">
                <div class="input-group">
                  <input class="form-control timepicker" type="text" name="end_time">
                    <span class="input-group-btn">
                         <button class="btn red" type="button">End Time <i class="fa fa-clock-o"></i></button>
                    </span>
                </div>
                <!-- /input-group -->
            </div>
            <!-- /.col-md-6 -->
        </div>
        
  
        <input type="hidden" name="task_id" id="task_id" value="{{$task->id}}" />
        <input type="hidden" name="user_id" id="user_id" value="{{$task->getUser->id}}"/>
        
        </form>
        @endif